
-- create table mktg_dev.sdey_filled_orders_2019_gcn as
-- SELECT
-- 	DATE_PART(year, CONVERT_TIMEZONE ('UTC', 'America/New_York', order_claim.ordered_timestamp))::integer AS ordered_timestamp_year,
-- 	gcn1.gcn_seqno,
-- 	gcn1.gcn,
-- 	COUNT(DISTINCT CASE WHEN order_claim.fill_sequence IS NOT NULL THEN
-- 			order_claim.order_id
-- 		ELSE
-- 			NULL
-- 		END) AS filled_orders
-- FROM
-- 	dwh.fact_order_item AS order_claim
-- 	LEFT JOIN dwh.dim_gcn_seqno_hierarchy AS gcn1 ON order_claim.last_claim_gcn_seqno_approved = gcn1.gcn_seqno
-- 	LEFT JOIN dwh.dim_user AS dim_user ON order_claim.dw_user_id = dim_user.dw_user_id
-- 		AND order_claim.account_id = dim_user.account_id
-- WHERE ((((order_claim.ordered_timestamp) >= ((CONVERT_TIMEZONE ('America/New_York', 'UTC', TIMESTAMP '2019-01-01')))
-- 			AND(order_claim.ordered_timestamp) < ((CONVERT_TIMEZONE ('America/New_York', 'UTC', DATEADD (year, 1, TIMESTAMP '2019-01-01')))))))
-- AND(NOT(gcn1.gcn_seqno IS NULL))
-- AND(NOT(gcn1.gcn IS NULL))
-- AND(dim_user.is_internal = FALSE
-- 	AND dim_user.is_phantom = FALSE
-- 	AND order_claim.is_fraud = FALSE)
-- GROUP BY
-- 	1,
-- 	2,
-- 	3
-- ORDER BY
-- 	4 DESC;

SELECT
	gcn,
	gcn_seqno,
	hicl_seqno,
	hicl_seqno_form,
	hicl_desc,
	brand_med_name,
	gtc_desc,
	stc_desc,
	ctc_desc,
	strength,
	form,
	maint_flg,
	dea_flg,
	opioid_flg,
	available_med_flg,
	tem_available_med_flg,
	default_gcn_flag,
	edlp_priced_flg,
	bsd_priced_flg,
	hd_priced_flg,
	grx_tracked_flg,
	blink_gcn_rank,
	blink_hicl_gcn_rank,
	blink_hicl_rank,
	blink_r30_gcn_rank,
	blink_r30_hicl_rank,
	symphony_2017_scripts,
	symphony_2017_pct_of_hicl_scripts,
	blink_pct_of_hicl_scripts,
	bh01_mac_price,
	bh02_mac_price,
	bh03_mac_price,
	wmt_mac_price,
	hd_syr_mac_price,
	bh01_dispensing_fee,
	bh01_dispensing_fee AS bh02_dispensing_fee,
	bh01_dispensing_fee AS bh03_dispensing_fee,
	wmt_dispensing_fee,
	hd_syr_dispensing_fee,
	gpi_gcn_mac_list_conflict_flg,
	fixed_stripe_charge_cost,
	variable_stripe_charge_cost,
	pac_unit,
	pac_low_unit,
	pac_high_unit,
	pac_retail_unit,
	r90_wmt_unc_unit_cost,
	r90_pblx_unc_unit_cost,
	r90_beh_unc_unit_cost,
	awp_unit_cost,
	ger_wmt_mac,
	wmt_script_pct,
	edlp_script_pct,
	bsd_script_pct,
	hd_script_pct,
	wmt_nfp_script_pct,
	edlp_nfp_script_pct,
	bsd_nfp_script_pct,
	hd_nfp_script_pct,
	edlp_fixed_price,
	edlp_unit_price,
	bsd_fixed_price,
	bsd_unit_price,
	hd_fixed_price,
	hd_unit_price,
	ltd_filling_patients,
	ltd_scripts,
	ltd_qty,
	ltd_nfp,
	ltd_nfp_scripts,
	ltd_nfp_qty,
	r30_scripts,
	r30_qty,
	r30_nfp_scripts,
	r30_nfp_qty,
	r30_wmt_scripts,
	r30_wmt_qty,
	r30_wmt_nfp_scripts,
	r30_wmt_nfp_qty,
	r30_edlp_scripts,
	r30_edlp_qty,
	r30_edlp_nfp_scripts,
	r30_edlp_nfp_qty,
	r30_bsd_scripts,
	r30_bsd_qty,
	r30_bsd_nfp_scripts,
	r30_bsd_nfp_qty,
	r30_hd_scripts,
	r30_hd_qty,
	r30_hd_nfp_scripts,
	r30_hd_nfp_qty,
	r30_bh01_edlp_scripts,
	r30_bh01_edlp_qty,
	r30_bh01_edlp_nfp_scripts,
	r30_bh01_edlp_nfp_qty,
	r30_bh02_edlp_scripts,
	r30_bh02_edlp_qty,
	r30_bh02_edlp_nfp_scripts,
	r30_bh02_edlp_nfp_qty,
	r30_bh03_edlp_scripts,
	r30_bh03_edlp_qty,
	r30_bh03_edlp_nfp_scripts,
	r30_bh03_edlp_nfp_qty,
	r30_bh01_bsd_scripts,
	r30_bh01_bsd_qty,
	r30_bh01_bsd_nfp_scripts,
	r30_bh01_bsd_nfp_qty,
	r30_bh02_bsd_scripts,
	r30_bh02_bsd_qty,
	r30_bh02_bsd_nfp_scripts,
	r30_bh02_bsd_nfp_qty,
	r30_bh03_bsd_scripts,
	r30_bh03_bsd_qty,
	r30_bh03_bsd_nfp_scripts,
	r30_bh03_bsd_nfp_qty,
	default_quantity,
	blink_edlp_price,
	blink_bsd_price,
	blink_hd_price,
	edlp_vs_bsd_gap,
	edlp_vs_hd_gap,
	bsd_vs_hd_gap,
	min_grx,
	min_retail_grx,
	min_bh_retail_index_grx,
	min_grx_northeast,
	min_grx_south,
	min_grx_midwest,
	min_grx_west,
	min_hwh_grx,
	min_cvs_grx,
	min_wag_grx,
	min_wmt_grx,
	min_rad_grx,
	min_kr_grx,
	min_sfwy_grx,
	min_pblx_grx,
	min_bksh_grx,
	min_geagle_grx,
	min_heb_grx,
	lowest_tracked_price_grx_pharmacy,
	lowest_tracked_grx_price,
	lowest_tracked_grx_pharmacy_type,
	wmt_2018_07_27_flg,
	wmt_2018_07_27_qty1,
	wmt_2018_07_27_price1,
	wmt_2018_07_27_qty2,
	wmt_2018_07_27_price2,
	wmt_2018_11_28_flg,
	wmt_2018_11_28_qty1,
	wmt_2018_11_28_price1,
	wmt_2018_11_28_qty2,
	wmt_2018_11_28_price2,
	wmt_retail_list_comp_price,
	pblx_2018_10_12_flg,
	pblx_2018_10_12_qty1,
	pblx_2018_10_12_price1,
	pblx_2018_10_12_qty2,
	pblx_2018_10_12_price2,
	wmt_est_unc_price,
	pblx_est_unc_price,
	beh_est_unc_price,
	edlp_grx_price_leader,
	edlp_min_retail_grx_price_leader,
	edlp_min_bh_retail_index_grx_price_leader,
	edlp_min_wmt_grx_price_leader,
	edlp_vs_min_grx_gap,
	edlp_vs_min_bh_retail_index_grx_gap,
	edlp_vs_min_wmt_grx_gap,
	bsd_vs_min_grx_gap,
	bsd_vs_min_bh_retail_index_grx_gap,
	bsd_vs_min_wmt_grx_gap,
	hd_vs_min_grx_gap,
	hd_vs_min_bh_retail_index_grx_gap,
	hd_vs_min_wmt_grx_gap,
	hd_vs_hwh_grx_gap,
	hicl_normalized_12_mos_30ds_scripts_per_nfp,
	hicl_form_normalized_12_mos_30ds_scripts_per_nfp,
	gcn_normalized_12_mos_30ds_scripts_per_nfp,
	projected_gcn_12_mos_30ds_normalized_scripts_from_nfp_scripts,
	r30_gcn_viewed_product_sessions,
	r30_gcn_purchased_product_sessions,
	r30_gcn_filled_product_sessions,
	r30_gcn_purchased_cvr,
	r30_gcn_filled_cvr,
	r30_gcn_purchase_to_fill_rate,
	r30_wmt_gross_revenue,
	r30_wmt_cogs,
	r30_wmt_ger_true_up,
	r30_wmt_gp,
	r30_wmt_gp_net_tu,
	r30_wmt_awp_filled,
	r30_wmt_mac_paid,
	r30_edlp_gross_revenue,
	r30_edlp_cogs,
	r30_edlp_gp,
	r30_bsd_gross_revenue,
	r30_bsd_cogs,
	r30_bsd_gp,
	r30_hd_gross_revenue,
	r30_hd_cogs,
	r30_hd_gp,
	r30_gross_revenue,
	r30_cogs,
	r30_gp,
	r30_wmt_ger_true_up AS r30_ger_true_up,
	r30_gp_net_ger_tu,
	r30_edlp_bh01_gross_revenue,
	r30_edlp_bh02_gross_revenue,
	r30_edlp_bh03_gross_revenue,
	r30_bsd_bh01_gross_revenue,
	r30_bsd_bh02_gross_revenue,
	r30_bsd_bh03_gross_revenue,
	r30_edlp_bh01_cogs,
	r30_edlp_bh02_cogs,
	r30_edlp_bh03_cogs,
	r30_bsd_bh01_cogs,
	r30_bsd_bh02_cogs,
	r30_edlp_bh01_gp,
	r30_edlp_bh02_gp,
	r30_edlp_bh03_gp,
	r30_bsd_bh01_gp,
	r30_bsd_bh02_gp,
	r30_bsd_bh03_gp,
	top_30ds_quantity,
	blink_edlp_price_30ds,
	blink_bsd_price_30ds,
	blink_hd_price_30ds,
	top_90ds_quantity,
	blink_edlp_price_90ds,
	blink_bsd_price_90ds,
	blink_hd_price_90ds,
	last_30ds_qty_scrape_date,
	last_30ds_qty,
	min_grx_30ds,
	min_retail_grx_30ds,
	min_bh_retail_index_grx_30ds,
	min_hwh_grx_30ds,
	min_wmt_grx_30ds,
	min_kr_grx_30ds,
	min_sfwy_grx_30ds,
	min_pblx_grx_30ds,
	min_bksh_grx_30ds,
	min_geagle_grx_30ds,
	min_heb_grx_30ds,
	last_90ds_qty_scrape_date,
	last_90ds_qty,
	min_grx_90ds,
	min_retail_grx_90ds,
	min_bh_retail_index_grx_90ds,
	min_hwh_grx_90ds,
	min_wmt_grx_90ds,
	min_kr_grx_90ds,
	min_sfwy_grx_90ds,
	min_pblx_grx_90ds,
	min_bksh_grx_90ds,
	min_geagle_grx_90ds,
	min_heb_grx_90ds,
	ltd_30_day_scripts,
	ltd_90_day_scripts,
	ltd_30_day_scripts_pct,
	ltd_90_day_scripts_pct,
	r30_30_day_scripts,
	r30_90_day_scripts,
	r30_30_day_script_pct,
	r30_90_day_script_pct,
	r30_30_day_nfp_scripts,
	r30_90_day_nfp_scripts,
	r30_30_day_nfp_script_pct,
	r30_90_day_nfp_script_pct,
	r30_hd_30_day_scripts,
	r30_hd_90_day_scripts,
	r30_hd_30_day_script_pct,
	r30_hd_90_day_script_pct,
	r30_hd_30_day_nfp_scripts,
	r30_hd_90_day_nfp_scripts,
	r30_hd_30_day_nfp_script_pct,
	r30_hd_90_day_nfp_script_pct
FROM
	fifo.generic_price_portfolio_datamart
ORDER BY
	blink_gcn_rank ASC
