SELECT
	tguh.gcn,
	tguh.med_id,
	tguh.gcn_seqno,
	tguh.pharmacy_network_id,
	tguh.pharmacy_network_name,
	tguh.in_consideration,
	tguh.in_consideration_reason,
	tguh.fills,
	tguh.margin,
	tguh.orders,
	tguh.revenue,
	tguh.users,
	gppd.gcn AS gcn_gppd,
	gppd.hicl_desc,
	gppd.brand_med_name,
	gppd.strength,
	gppd.form,
	gppd.default_quantity,
	gppd.blink_hicl_rank,
	gppd.top_30ds_quantity,
	gppd.top_90ds_quantity,
	gppd.edlp_unit_price,
	gppd.bsd_unit_price,
	gppd.hd_unit_price,
	gppd.edlp_fixed_price,
	gppd.bsd_fixed_price,
	gppd.hd_fixed_price,
	gppd.bh01_mac_price,
	gppd.bh02_mac_price,
	gppd.bh03_mac_price,
	gppd.wmt_mac_price,
	gppd.hd_syr_mac_price,
	gppd.bh01_dispensing_fee,
	gppd.bh02_dispensing_fee,
	gppd.bh03_dispensing_fee,
	gppd.wmt_dispensing_fee,
	gppd.hd_syr_dispensing_fee,
	gppd.wmt_2018_11_28_qty1,
	gppd.wmt_2018_11_28_qty2,
	gppd.wmt_2018_11_28_price1,
	gppd.wmt_2018_11_28_price2,
	gppd.wmt_2018_11_28_flg,
	gppd.last_30ds_qty,
	gppd.last_90ds_qty,
	gppd.min_grx_30ds,
	gppd.min_grx_90ds,
	gppd.min_major_retail_grx_30ds,
	gppd.min_major_retail_grx_90ds,
	gppd.min_retail_grx_30ds,
	gppd.min_retail_grx_90ds,
	gppd.last_30ds_qty_scrape_date,
	gppd.ltd_30_day_scripts,
	gppd.ltd_90_day_scripts,
	gppd.ltd_30_day_scripts_pct,
	gppd.ltd_90_day_scripts_pct,
	gppd.r30_30_day_scripts,
	gppd.r30_90_day_scripts,
	gppd.r30_30_day_script_pct,
	gppd.r30_90_day_script_pct
FROM
	mktg_dev.sdey_target_gcns_with_updated_history AS tguh
LEFT OUTER JOIN
	fifo.generic_price_portfolio_datamart AS gppd
ON
	tguh.gcn = gppd.gcn
	AND tguh.gcn_seqno = gppd.gcn_seqno
WHERE
	margin < -300
